Завдання 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та
виведіть його значення.

In [3]:
import numpy as np

# Створюємо одновимірний масив з першими 10-ма натуральними числами
vector = np.arange(1, 11)

# Виводимо значення масиву
vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Завдання 2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та
виведіть його значення.

In [2]:
import numpy as np

# Створюємо двовимірний масив (матрицю) розміром 4x4, заповнений одиницями
matrix = np.ones((4, 4))

# Виводимо значення матриці
print(matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Завдання 3. Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні
від 1 до 5 та виведіть його значення.

In [4]:
import numpy as np

# Створюємо двовимірний масив (матрицю) розміром 4x4, заповнений випадковими цілими числами від 1 до 5
matrix = np.random.randint(1, 6, size=(4, 4))

# Виводимо значення матриці
print(matrix)


[[3 1 4 1]
 [2 5 4 3]
 [4 2 3 2]
 [3 2 3 3]]


Завдання 4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та виведіть його значення

In [5]:
import numpy as np

# Створюємо двовимірний масив (матрицю) розміром 3x3, заповнений випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

# Виводимо значення матриці
print(matrix)


[[0.76070728 0.24889347 0.92327248]
 [0.50376761 0.66449953 0.18411603]
 [0.48113823 0.88038446 0.10664417]]


Завдання 5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими
числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання,
віднімання та множення

In [6]:
import numpy as np

# Створюємо два одновимірних масиви розміром 6, заповнені випадковими цілими числами від 1 до 20
array1 = np.random.randint(1, 21, size=6)
array2 = np.random.randint(1, 21, size=6)

# Поелементне додавання
addition = array1 + array2

# Поелементне віднімання
subtraction = array1 - array2

# Поелементне множення
multiplication = array1 * array2

# Виводимо значення масивів та результати операцій
print("Масив 1:", array1)
print("Масив 2:", array2)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)


Масив 1: [11 15 11 10 13 20]
Масив 2: [12  4 14 18 19 11]
Додавання: [23 19 25 28 32 31]
Віднімання: [-1 11 -3 -8 -6  9]
Множення: [132  60 154 180 247 220]


Завдання 6. Створіть два матриці 2x2, заповніть їх довільними цілими числами та знайдіть їх
добуток.

In [7]:
import numpy as np

# Створюємо дві матриці розміром 2x2, заповнені довільними цілими числами
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Знаходимо їх добуток
product = np.dot(matrix1, matrix2)

# Виводимо значення матриць та їх добуток
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nДобуток матриць:")
print(product)


Матриця 1:
[[1 2]
 [3 4]]

Матриця 2:
[[5 6]
 [7 8]]

Добуток матриць:
[[19 22]
 [43 50]]


Завдання 7. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 10 та перемножте їх між собою.


In [8]:
import numpy as np

# Створюємо матрицю розміром 3x2 з випадковими цілими числами від 1 до 10
matrix_3x2 = np.random.randint(1, 11, size=(3, 2))
print("Матриця 3x2:")
print(matrix_3x2)

# Створюємо матрицю розміром 2x4 з випадковими цілими числами від 1 до 10
matrix_2x4 = np.random.randint(1, 11, size=(2, 4))
print("\nМатриця 2x4:")
print(matrix_2x4)

# Перемножуємо матриці
result = np.dot(matrix_3x2, matrix_2x4)
print("\nРезультат множення матриць:")
print(result)


Матриця 3x2:
[[3 5]
 [3 7]
 [7 4]]

Матриця 2x4:
[[ 8  3  8  9]
 [ 6  2  2 10]]

Результат множення матриць:
[[ 54  19  34  77]
 [ 66  23  38  97]
 [ 80  29  64 103]]


Завдання 8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 7 та знайдіть її обернену матрицю

In [9]:
import numpy as np

# Створюємо матрицю розміром 2x2 з випадковими цілими числами від 1 до 7
matrix_2x2 = np.random.randint(1, 8, size=(2, 2))
print("Матриця 2x2:")
print(matrix_2x2)

# Перевіряємо, чи матриця є оберненою (не вироджена)
if np.linalg.det(matrix_2x2) != 0:
    # Знаходимо обернену матрицю
    inverse_matrix = np.linalg.inv(matrix_2x2)
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("\nМатриця є виродженою і не має оберненої матриці.")


Матриця 2x2:
[[7 2]
 [4 5]]

Обернена матриця:
[[ 0.18518519 -0.07407407]
 [-0.14814815  0.25925926]]


Завдання 9. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.


In [10]:
import numpy as np

# Створюємо матрицю розміром 3x3 з випадковими дійсними числами від 0 до 1
matrix_3x3 = np.random.rand(3, 3)
print("Матриця 3x3:")
print(matrix_3x3)

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix_3x3)
print("\nТранспонована матриця:")
print(transposed_matrix)


Матриця 3x3:
[[0.78046787 0.4124374  0.45417469]
 [0.47794448 0.72802439 0.51218966]
 [0.36560118 0.62271367 0.43701887]]

Транспонована матриця:
[[0.78046787 0.47794448 0.36560118]
 [0.4124374  0.72802439 0.62271367]
 [0.45417469 0.51218966 0.43701887]]


Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.

In [11]:
import numpy as np

# Створюємо матрицю розміром 3x4 з випадковими цілими числами від 1 до 10
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
print("Матриця 3x4:")
print(matrix_3x4)

# Створюємо вектор розміром 4x1 з випадковими цілими числами від 1 до 10
vector_4x1 = np.random.randint(1, 11, size=(4, 1))
print("\nВектор 4x1:")
print(vector_4x1)

# Знаходимо добуток матриці на вектор
product = np.dot(matrix_3x4, vector_4x1)
print("\nДобуток матриці на вектор:")
print(product)


Матриця 3x4:
[[2 3 1 6]
 [8 9 7 3]
 [4 6 6 6]]

Вектор 4x1:
[[3]
 [3]
 [8]
 [6]]

Добуток матриці на вектор:
[[ 59]
 [125]
 [114]]


Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [12]:
import numpy as np

# Створюємо матрицю розміром 2x3 з випадковими цілими числами від 1 до 10
matrix_2x3 = np.random.randint(1, 11, size=(2, 3))
print("Матриця 2x3:")
print(matrix_2x3)

# Створюємо вектор розміром 3x1 з випадковими цілими числами від 1 до 10
vector_3x1 = np.random.randint(1, 11, size=(3, 1))
print("\nВектор 3x1:")
print(vector_3x1)

# Знаходимо добуток матриці на вектор
product = np.dot(matrix_2x3, vector_3x1)
print("\nДобуток матриці на вектор:")
print(product)


Матриця 2x3:
[[5 4 8]
 [7 1 2]]

Вектор 3x1:
[[ 1]
 [10]
 [ 1]]

Добуток матриці на вектор:
[[53]
 [19]]


Завдання 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню суму.

In [13]:
import numpy as np

# Створюємо першу матрицю розміром 2x2 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
print("Матриця 1:")
print(matrix1)

# Створюємо другу матрицю розміром 2x2 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(2, 2))
print("\nМатриця 2:")
print(matrix2)

# Знаходимо суму матриць
matrix_sum = matrix1 + matrix2
print("\nСума матриць:")
print(matrix_sum)


Матриця 1:
[[8 2]
 [9 8]]

Матриця 2:
[[10  9]
 [ 4  6]]

Сума матриць:
[[18 11]
 [13 14]]


Завдання 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть їх добуток.

In [14]:
import numpy as np

# Створюємо першу матрицю розміром 2x2 з випадковими дійсними числами від 0 до 1
matrix1 = np.random.rand(2, 2)
print("Матриця 1:")
print(matrix1)

# Створюємо другу матрицю розміром 2x2 з випадковими дійсними числами від 0 до 1
matrix2 = np.random.rand(2, 2)
print("\nМатриця 2:")
print(matrix2)

# Знаходимо добуток матриць
matrix_product = np.dot(matrix1, matrix2)
print("\nДобуток матриць:")
print(matrix_product)


Матриця 1:
[[0.52779094 0.79867188]
 [0.57874525 0.53595518]]

Матриця 2:
[[0.97161149 0.00328154]
 [0.09188932 0.61609893]]

Добуток матриць:
[[0.58619716 0.49379286]
 [0.6115641  0.33210059]]


Завдання 14. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть суму елементів матриці.

In [15]:
import numpy as np

# Створюємо матрицю розміром 5x5 з випадковими дійсними числами від 0 до 1
matrix_5x5 = np.random.rand(5, 5)
print("Матриця 5x5:")
print(matrix_5x5)

# Знаходимо суму всіх елементів матриці
sum_of_elements = np.sum(matrix_5x5)
print("\nСума всіх елементів матриці:")
print(sum_of_elements)


Матриця 5x5:
[[0.59177806 0.742019   0.30782505 0.19719179 0.88516214]
 [0.11218548 0.21306998 0.909169   0.16710805 0.05431998]
 [0.28364197 0.80927981 0.93614106 0.69590865 0.07780506]
 [0.05884246 0.78158413 0.29288416 0.36659142 0.46209601]
 [0.27756911 0.31872362 0.21006642 0.75007868 0.49987903]]

Сума всіх елементів матриці:
11.000920126627275


Завдання 15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного
рядка матриці.

In [16]:
import numpy as np

# Створюємо матрицю розміром 3x3 з випадковими дійсними числами від -1 до 1
matrix_3x3 = np.random.uniform(-1, 1, size=(3, 3))
print("Матриця 3x3:")
print(matrix_3x3)

# Знаходимо суму елементів кожного рядка матриці
sum_of_rows = np.sum(matrix_3x3, axis=1)
print("\nВектор-стовпчик з сумами елементів кожного рядка:")
print(sum_of_rows)


Матриця 3x3:
[[-0.45351388  0.33186517 -0.41744222]
 [-0.00099141 -0.14085417  0.88670491]
 [ 0.12203862  0.34845427 -0.16457123]]

Вектор-стовпчик з сумами елементів кожного рядка:
[-0.53909092  0.74485934  0.30592166]


Ось висновок по роботі з матрицями та векторами:

### Висновок

1. **Створення матриць і векторів**:
   - Ми використали бібліотеку `numpy` для створення матриць та векторів різних розмірів і заповнення їх випадковими числами. Це дозволяє легко маніпулювати даними та виконувати математичні операції.

2. **Операції з матрицями і векторами**:
   - **Добуток матриці та вектора**: Ми обчислили добуток матриці розміром 3x4 на вектор розміром 4x1. Це показує, як матриці та вектори можуть бути використані для обчислень у лінійній алгебрі.
   - **Сума матриць**: Знайшли суму двох матриць розміром 2x2. Цей простий приклад демонструє, як елементи матриць можна додавати поелементно.
   - **Добуток матриць**: Обчислили добуток двох матриць розміром 2x2. Цей приклад показує, як матриці можна множити між собою.
   - **Сума елементів матриці**: Обчислили суму всіх елементів матриці розміром 5x5. Це показує, як легко можна агрегувати дані в матриці.
   - **Сума рядків матриці**: Знайшли вектор-стовпчик, що містить суму елементів кожного рядка матриці 3x3. Це корисно для статистичних аналізів або агрегаційних операцій.

3. **Практичне застосування**:
   - Робота з матрицями та векторами є основою для чисельних обчислень, які використовуються в чисельних методах, машинному навчанні, статистичному аналізі та інших галузях науки і техніки.
   - Вміння маніпулювати матрицями та векторами за допомогою бібліотеки `numpy` є важливим для обробки даних, моделювання і аналізу.

Ці навички допомагають вирішувати різноманітні математичні та прикладні задачі, використовуючи потужний інструментарій Python.